-- CreateEnum
CREATE TYPE "CompanyCategory" AS ENUM (
  'FOOD_AND_BEVERAGE',
  'RETAIL',
  'SERVICES',
  'HEALTH',
  'EDUCATION',
  'TECHNOLOGY',
  'CONSTRUCTION',
  'TRANSPORT',
  'TOURISM_AND_HOSPITALITY',
  'BEAUTY_AND_AESTHETICS',
  'AUTOMOTIVE',
  'REAL_ESTATE',
  'FINANCIAL',
  'ENTERTAINMENT',
  'FASHION_AND_APPAREL',
  'SPORTS_AND_FITNESS',
  'PET_SERVICES',
  'LEGAL',
  'CONSULTING',
  'MANUFACTURING',
  'AGRICULTURE',
  'ENERGY',
  'TELECOMMUNICATIONS',
  'MEDIA_AND_ADVERTISING',
  'NON_PROFIT',
  'OTHER'
);

-- AlterTable
ALTER TABLE "companies" ADD COLUMN "category" "CompanyCategory" NOT NULL DEFAULT 'OTHER';

